apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: devops-django
data:
  DEBUG: "0"
  ALLOWED_HOSTS: "*"
  CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq-service:5672//"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: devops-django
type: Opaque
stringData:
  SECRET_KEY: "production-grade-super-secret-key-change-me"